version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: ecom-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped
